CREATE SEQUENCE SQ_LIB INCREMENT BY 1 START WITH 100;


CREATE TABLE USERS
(
  ID         NUMBER       NOT NULL,
  LOGIN      VARCHAR(50)  NOT NULL,
  PASSWORD      VARCHAR(100)  NOT NULL,
  FIRST_NAME VARCHAR(200) NOT NULL,
  LAST_NAME  VARCHAR(200) NOT NULL,
  STATUS     VARCHAR(20)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES
(
  USER_ID         NUMBER       NOT NULL,
  ROLE      VARCHAR(50)  NOT NULL,
  CONSTRAINT FK_USER_ROLES FOREIGN KEY (USER_ID) REFERENCES
    USERS (ID) ON DELETE CASCADE
);

CREATE TABLE BOOK
(
  ID         NUMBER       NOT NULL,
  TITLE      VARCHAR(200)  NOT NULL,
  AUTHOR      VARCHAR(100)  NOT NULL,
  DESCRIPTION VARCHAR(2000) NOT NULL,
  PUBLICATION_YEAR  NUMBER(4,0) NOT NULL,
  PRICE DECIMAL (20, 2)       NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE DOWNLOADED_BOOK
(
  ID         NUMBER       NOT NULL,
  BOOK_ID      NUMBER       NOT NULL,
  USER_ID      NUMBER       NOT NULL,
  DATE TIMESTAMP  NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_DB_BOOK FOREIGN KEY (BOOK_ID) REFERENCES
    BOOK (ID) ON DELETE CASCADE,
  CONSTRAINT FK_DB_USER FOREIGN KEY (USER_ID) REFERENCES
    USERS (ID) ON DELETE CASCADE
);

